### ISSUE TITLE
Allow media uploads for objects

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs4teachers#45]
- https://docs.djangoproject.com/en/1.11/howto/custom-file-storage/
- https://googlecloudplatform.github.io/google-cloud-python/stable/storage-blobs.html

**Comment by ravenmaster001** [comment]
@JackMorganNZ Pretty sure this works now, the returned URL looks correct when I added a print in.

**Comment by JackMorganNZ** [comment]
Completed in 6dd3731.
